/* 
**  mod_noop.c -- Apache sample noop module
**  [Autogenerated via ``apxs -n noop -g'']
**
**  Compile via
**
**    $ apxs -c -i mod_noop.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /noop in as follows:
**
**    #   httpd.conf
**    LoadModule noop_module modules/mod_noop.so
**    <Location /noop>
**    SetHandler noop
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /noop and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ curl -vvv localhost/test.cgi
**
**  The output should be similar to the following one:
**
**    * About to connect() to localhost port 80 (#0)
**    *   Trying 127.0.0.1...
**    * Connected to localhost (127.0.0.1) port 80 (#0)
**    > GET /test.cgi HTTP/1.1
**    > User-Agent: curl/7.29.0
**    > Host: localhost
**    > Accept: *//*
**    >
**    < HTTP/1.1 200 OK
**    < Date: Thu, 02 Aug 2018 10:18:25 GMT
**    < Server: Apache/2.4.6 (CentOS)
**    < Content-Length: 0
**    < Content-Type: text/plain; charset=UTF-8
**    <
**    * Connection #0 to host localhost left intact
*/
#include "httpd.h"
#include "http_core.h"
#include "http_protocol.h"
#include "http_request.h"

static int noop_handler(request_rec *r) {
    ap_set_content_type(r, "text/plain");
    ap_rputs("", r);
    return OK;
}

static void noop_register_hooks(apr_pool_t *p) {
    ap_hook_handler(noop_handler, NULL, NULL, APR_HOOK_FIRST);
}

module AP_MODULE_DECLARE_DATA noop_module = {
    STANDARD20_MODULE_STUFF,
    NULL, NULL, NULL, NULL, NULL,
    noop_register_hooks
};
